name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
 
  Build:
    runs-on: self-hosted 

    steps:
  #  - uses: actions/checkout@v3
  #  - name: Build the Docker image
  #    run: docker build . --file Dockerfile --tag my-image-name:latest
  #  - name: run & test Container
  #    run: docker run -itd --name war-lidor -p 80:8080 my-image-name:latest
  #  - run: sleep 90 && curl localhost:8080
  
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: run & test Container
      run: docker run -itd --name war-tomer-and-jo -p 80:8080 my-image-name:latest
    - run: sleep 30 && curl localhost:8080

    - name: change image name 
      run: docker tag my-image-name:latest lordagam/github-repo-hello-world-war5:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker push
      run: docker push lordagam/github-repo-hello-world-war5:latest
      
 #   - Test:
 #     needs: Build
 #     runs-on: ubuntu-latest
 #     steps:
 #   
 #   - name: run & test Container
 #     run: docker run -itd --name python-hello -p 8080   my-image-name:latest
